version: "3"
services:
  app:
    build: ./app/
    command: python3 -u app/app.py --host db
    volumes:
    - .:/app
    ports:
      - "5000:5000"
      
  front:
    container_name: front
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true