version: "3"
services:
  app:
    container_name: app
    build: ./app/
    command: python3 -u app/app.py --host db
    volumes:
    - .:/app
    ports:
      - "5000:5000"
    links:
      - mongo
    networks:
      - backend
      - frontend
      
  front:
    container_name: front
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - frontend

  mongo:
    image: mongo:6.0.2
    networks:
      - backend

  mongo_seed:
    image: mongo:6.0.2
    links:
      - mongo
    networks:
      - backend
    volumes:
      - ./mongo-seed:/mongo-seed/
    command:
      /mongo-seed/import.sh

networks:
  backend:
    driver: "bridge"
  frontend:
    driver: "bridge"
